from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'planning/m4-review'
report=json.loads((out/'asset-report.json').read_text())
def figure(src,caption):
    return f'<figure><a href="{src}"><img loading="lazy" src="{src}" alt="{escape(caption)}"></a><figcaption>{escape(caption)}</figcaption></figure>'
comparisons=''
for label,photo,view in [('Front','152551','front-reference'),('Front left','152518','front-left'),('Front right','152613','front-right')]:
    comparisons+=f'<h3>{label}</h3><div class="pair">'+figure(f'../../research/references/google_maps_images/Screenshot%202026-01-02%20{photo}.png','Original Google reference, unchanged; see M1 for image dating')+figure(view+'.png','M4 browser view; approximate corresponding viewpoint, not a solved camera match')+'</div>'
views=[('room-daylight','Approved service-shop arrangement, daylight'),('crates','Left storeroom: empty crate racks and retained boxes'),('packing','Right storeroom: packing bench, paper roll, twine and hand truck'),('packing-detail','Close inspection of retained packing tools'),('passage','Continuous central passage to the rear exit'),('rear','Finished rear facade, open door, landing and steps'),('side-path','Side service path and restrained vegetation'),('site','Immediate roadside setting'),('road','Divided highway, median and neighboring context'),('room','Front room with switched lighting'),('crates-lit','Crate storeroom with switched lighting'),('window-open','Approved inward-tilting entrance return pane')]
gallery=''.join(figure(name+'.png',caption) for name,caption in views)
out.joinpath('index.html').write_text(f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>M4 / The complete old store</title><style>
*{{box-sizing:border-box}}body{{margin:0;background:#eeece3;color:#303b31;font:16px/1.6 system-ui}}header,main{{max-width:1400px;margin:auto;padding:32px}}h1{{font:64px/1 Georgia,serif;margin:22px 0}}h2{{margin-top:50px}}a{{color:#486440}}.eyebrow{{font-size:12px;letter-spacing:.15em}}.pair,.gallery{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}figure{{margin:0;background:#fff}}img{{display:block;width:100%;aspect-ratio:16/10;object-fit:contain;background:#20281f}}figcaption{{padding:16px;font-size:14px}}.metrics{{padding:22px;background:#d9dece}}nav{{display:flex;gap:24px;flex-wrap:wrap}}@media(max-width:750px){{.pair,.gallery{{grid-template-columns:1fr}}h1{{font-size:44px}}}}
</style><header><div class="eyebrow">M4 / BUILDING AND ENVIRONMENT</div><h1>The old store,<br>from front to back.</h1><p>The approved produce-service shop, two furnished storerooms, rear passage and immediate roadside surroundings.</p><nav><a href="http://127.0.0.1:5173/">Explore locally</a><a href="https://app.notion.com/p/3d2488886d578105935cd7ff2897d3e4">Notion issue</a><a href="../m4-review.md">Verification and provenance</a><a href="../../model/myrtle-beach-v2-complete.blend">Blender source</a></nav></header><main><div class="metrics">{report['triangles']:,} source triangles · {report['meshObjects']} render meshes · {report['glbBytes']/1e6:.2f} MB GLB · {report['estimatedTextureMiBWithMipmaps']:.1f} MiB conservative texture estimate</div><h2>Room-by-room and site review</h2><p>Interior furnishings and undocumented site details are imagined. The researched exterior and approved M3 arrangement remain the basis. Independent room switching and full opening controls are M5 work.</p><div class="gallery">{gallery}</div><h2>Exterior evidence comparisons</h2><p>Original reference screenshots retain their attribution. Compare the facade openings, canopy, stepped parapets and chimney. Site distances and vegetation are contextual estimates.</p>{comparisons}<h2>Verification records</h2><p><a href="browser-report.json">Chrome interaction regression</a> · <a href="full-scene-report.json">Full-scene navigation and performance</a> · <a href="edge-report.json">Edge verification</a> · <a href="asset-report.json">Asset inventory</a> · <a href="window-clearance.json">Entrance mesh clearance</a></p></main></html>''',encoding='utf-8')
print(out/'index.html')
